suite for unit tests added
yiisoft-contrib/github-bot pull request #8
Opened 2016-11-19 17:58 UTC by dynasource

Test suite is added for github bot:
- phpunit.xml + bootstrap + TestCase.php
- mock files for github api
- tests for components/Github.php
- tests for commands/GithubController.php

2016-11-19 19:51 UTC, cebe requested changes

2016-11-19 19:51 UTC, cebe commented on .gitignore
> +/.idea/*
you should put this into your [global gitignore](https://gist.github.com/cebe/1166792#file-gitconfig-L27) file. The repo should only contain repo specific ignores.

2016-11-19 19:51 UTC, cebe commented on tests/bootstrap.php
> +    $vendorRoot = __DIR__ . '/../../..'; //this extension is part of a project vendor folder
this seems to be not needed for github-bot.

2016-11-19 19:51 UTC, cebe commented on components/Github.php
> +        $client = YII_ENV_TEST ? new CachedHttpClientMock() : new \Github\HttpClient\CachedHttpClient();
better use DI container to create this instance and replace it in test env.

2016-11-19 19:51 UTC, cebe commented on commands/GithubController.php
> +                $api = YII_ENV_TEST ? new RepoMock($client) : new Repo($client);
better use DI container to create this instance and replace it in test env.

2016-11-19 19:56 UTC, dynasource commented on tests/bootstrap.php
> +    $vendorRoot = __DIR__ . '/../../..'; //this extension is part of a project vendor folder
true

2016-11-21 21:18 UTC, closed without merging

2016-11-21 21:18 UTC, cebe commented
merged, thank you!